name: test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - release
      - gh-action-update

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out mitiq
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          make install requirements

      # Not checking types until #556 fixes errors 
      # - name: Check types with MyPy
      #   run: make check-types

      - name: Check code style with Black
        run: make check-format || echo "run make format to resolve issues"

      - name: Lint with flake8
        run: make check-style

      - name: Build and test Sphinx docs
        run: |
          make docs
          make doctest

  # runs just the main & benchmarking tests on py37/38 and mac/windows
  test:
    # Reduces running tests if the validation dosen't pass
    # https://stackoverflow.com/a/65698892/10022996
    needs: validate
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.7, 3.8]
    
    steps:
      - name: Check out mitiq
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          make install requirements
      - name: Run the mitiq unit tests via pytest
        run: make test